### ISSUE TITLE
New Year

### ISSUE THREAD

**Issue by LizzWilk** [UnlockedLab/unlockphilly#58]
Checking in

**Comment by jamestyack** [comment]
Lovely @LizzWilk please fix some bugs !!

**Comment by LizzWilk** [comment]
Wow. Chamomile tea time?

**Comment by jamestyack** [comment]
:)  not at all, pretty chilled out!  I'm at a weekend hack event at Indy hall.

**Comment by LizzWilk** [comment]
Cool !! Then more La Columbe!
